- name: add facts from OpenStack discovery
  set_fact:
    ansible_ssh_host: "{{ hostvars[inventory_hostname].openstack.addresses.net_mgmt[0].addr }}"
    ansible_ssh_user: "root"

- name: Display all variables/facts known for a host
  debug: var=hostvars[inventory_hostname] verbosity=4

- name: Wait for port 22 to become open
  local_action: wait_for port=22 host="{{ ansible_ssh_host | default(inventory_hostname) }}" search_regex=OpenSSH delay=10 timeout=1200

- name: Add service to titan
  uri: method=POST force_basic_auth=yes url=http://localhost/api/v1/servicesmngt/services user=Administrator password=titan body="{{ lookup('files', 'titan_service.json') }}" body_format=json
